package it.esercitazione4.visitor;

import it.esercitazione4.nodes.AssignStatNode;
import it.esercitazione4.nodes.BoolConstLeaf;
import it.esercitazione4.nodes.CallProcNode;
import it.esercitazione4.nodes.ElifListNode;
import it.esercitazione4.nodes.ElifNode;
import it.esercitazione4.nodes.ElseNode;
import it.esercitazione4.nodes.ExprListNode;
import it.esercitazione4.nodes.ExprNode;
import it.esercitazione4.nodes.FloatConstLeaf;
import it.esercitazione4.nodes.IdLeaf;
import it.esercitazione4.nodes.IdListInitNode;
import it.esercitazione4.nodes.IdListNode;
import it.esercitazione4.nodes.IfStatNode;
import it.esercitazione4.nodes.IntConstLeaf;
import it.esercitazione4.nodes.NullConstLeaf;
import it.esercitazione4.nodes.ParDeclNode;
import it.esercitazione4.nodes.ParamDeclListNode;
import it.esercitazione4.nodes.ProcListNode;
import it.esercitazione4.nodes.ProcNode;
import it.esercitazione4.nodes.ProgramNode;
import it.esercitazione4.nodes.ReadlnStatNode;
import it.esercitazione4.nodes.ResultTypeListNode;
import it.esercitazione4.nodes.ResultTypeNode;
import it.esercitazione4.nodes.ReturnExprsNode;
import it.esercitazione4.nodes.StatListNode;
import it.esercitazione4.nodes.StringConstLeaf;
import it.esercitazione4.nodes.TypeDeclNode;
import it.esercitazione4.nodes.VarDeclListNode;
import it.esercitazione4.nodes.VarDeclNode;
import it.esercitazione4.nodes.WhileStatNode;
import it.esercitazione4.nodes.WriteStatNode;

public interface Visitor {
    public Object visit(AssignStatNode node);
    public Object visit(BoolConstLeaf leaf);
    public Object visit(CallProcNode node);
    public Object visit(ElifListNode node);
    public Object visit(ElifNode node);
    public Object visit(ElseNode node);
    public Object visit(ExprListNode node);
    public Object visit(ExprNode node);
    public Object visit(FloatConstLeaf leaf);
    public Object visit(IdLeaf leaf);
    public Object visit(IdListInitNode node);
    public Object visit(IdListNode node);
    public Object visit(IfStatNode node);
    public Object visit(IntConstLeaf leaf);
    public Object visit(NullConstLeaf leaf);
    public Object visit(ParamDeclListNode node);
    public Object visit(ParDeclNode node);
    public Object visit(ProcListNode node);
    public Object visit(ProcNode node);
    public Object visit(ProgramNode node);
    public Object visit(ReadlnStatNode node);
    public Object visit(ResultTypeListNode node);
    public Object visit(ResultTypeNode node);
    public Object visit(ReturnExprsNode node);
    public Object visit(StatListNode node);
    public Object visit(StringConstLeaf leaf);
    public Object visit(TypeDeclNode node);
    public Object visit(VarDeclListNode node);
    public Object visit(VarDeclNode node);
    public Object visit(WhileStatNode node);
    public Object visit(WriteStatNode node);
}
