package it.esercitazione4.visitor;

import it.esercitazione4.nodes.AssignStatNode;
import it.esercitazione4.nodes.BoolConstLeaf;
import it.esercitazione4.nodes.CallProcNode;
import it.esercitazione4.nodes.ElifListNode;
import it.esercitazione4.nodes.ElifNode;
import it.esercitazione4.nodes.ElseNode;
import it.esercitazione4.nodes.ExprListNode;
import it.esercitazione4.nodes.ExprNode;
import it.esercitazione4.nodes.FloatConstLeaf;
import it.esercitazione4.nodes.IdLeaf;
import it.esercitazione4.nodes.IdListInitNode;
import it.esercitazione4.nodes.IdListNode;
import it.esercitazione4.nodes.IfStatNode;
import it.esercitazione4.nodes.IntConstLeaf;
import it.esercitazione4.nodes.NullConstLeaf;
import it.esercitazione4.nodes.ParDeclNode;
import it.esercitazione4.nodes.ParamDeclListNode;
import it.esercitazione4.nodes.ProcListNode;
import it.esercitazione4.nodes.ProcNode;
import it.esercitazione4.nodes.ProgramNode;
import it.esercitazione4.nodes.ReadlnStatNode;
import it.esercitazione4.nodes.ResultTypeListNode;
import it.esercitazione4.nodes.ResultTypeNode;
import it.esercitazione4.nodes.ReturnExprsNode;
import it.esercitazione4.nodes.StatListNode;
import it.esercitazione4.nodes.StringConstLeaf;
import it.esercitazione4.nodes.TypeDeclNode;
import it.esercitazione4.nodes.VarDeclListNode;
import it.esercitazione4.nodes.VarDeclNode;
import it.esercitazione4.nodes.WhileStatNode;
import it.esercitazione4.nodes.WriteStatNode;

public interface Visitor {
    public Object visit(AssignStatNode node) throws Exception;
    public Object visit(BoolConstLeaf leaf) throws Exception;
    public Object visit(CallProcNode node) throws Exception;
    public Object visit(ElifListNode node) throws Exception;
    public Object visit(ElifNode node) throws Exception;
    public Object visit(ElseNode node) throws Exception;
    public Object visit(ExprListNode node) throws Exception;
    public Object visit(ExprNode node) throws Exception;
    public Object visit(FloatConstLeaf leaf) throws Exception;
    public Object visit(IdLeaf leaf) throws Exception;
    public Object visit(IdListInitNode node) throws Exception;
    public Object visit(IdListNode node) throws Exception;
    public Object visit(IfStatNode node) throws Exception;
    public Object visit(IntConstLeaf leaf) throws Exception;
    public Object visit(NullConstLeaf leaf) throws Exception;
    public Object visit(ParamDeclListNode node) throws Exception;
    public Object visit(ParDeclNode node) throws Exception;
    public Object visit(ProcListNode node) throws Exception;
    public Object visit(ProcNode node) throws Exception;
    public Object visit(ProgramNode node) throws Exception;
    public Object visit(ReadlnStatNode node) throws Exception;
    public Object visit(ResultTypeListNode node) throws Exception;
    public Object visit(ResultTypeNode node) throws Exception;
    public Object visit(ReturnExprsNode node) throws Exception;
    public Object visit(StatListNode node) throws Exception;
    public Object visit(StringConstLeaf leaf) throws Exception;
    public Object visit(TypeDeclNode node) throws Exception;
    public Object visit(VarDeclListNode node) throws Exception;
    public Object visit(VarDeclNode node) throws Exception;
    public Object visit(WhileStatNode node) throws Exception;
    public Object visit(WriteStatNode node) throws Exception;
}
